/* ---------- USERS ---------- */
-- USERS
INSERT INTO APP_USER (USER_ID, USERNAME, EMAIL, PASSWORD) 
VALUES (1, 'NATC', 'NCHIMBAY@GMAIL.COM', 'NEWARKJULY1');

INSERT INTO APP_USER (USER_ID, USERNAME, EMAIL, PASSWORD) 
VALUES (2, 'MUNAU', 'MCHISMO@GMAIL.COM', 'ROSELLE31');

INSERT INTO APP_USER(USER_ID, USERNAME, EMAIL, PASSWORD)
VALUES (3, 'JOSEPH', 'JGARCIA@GMAIL,COM', 'JOSEPH2005');

INSERT INTO APP_USER(USER_ID, USERNAME, EMAIL, PASSWORD)
VALUES (4, 'ARYSWAGGY', 'ARYAD@GMAIL,COM', 'ARYTHECOOLMAN');

INSERT INTO APP_USER(USER_ID, USERNAME, EMAIL, PASSWORD)
VALUES(5,'EbelechukwuNwafor','Ebelechukwu.N@ghmail.com','BESTPROF');


/* ---------- ARTISTS ---------- */ 
INSERT INTO ARTIST (ARTIST_ID, NAME) 
VALUES (201, 'Bad Bunny');

INSERT INTO ARTIST (ARTIST_ID, NAME) 
VALUES (202, 'Clairo');

INSERT INTO ARTIST (ARTIST_ID, NAME) 
VALUES (203, 'Mitski');

INSERT INTO ARTIST (ARTIST_ID, NAME) 
VALUES (204, 'GenerationX');

INSERT INTO ARTIST (ARTIST_ID, NAME) 
VALUES (205, 'DRAKE');


/* ---------- SONGS ---------- */
INSERT INTO SONG (SONG_ID, TITLE, RELEASE_YEAR) 
VALUES (101, 'EoO', 2025);

INSERT INTO SONG (SONG_ID, TITLE, RELEASE_YEAR) 
VALUES (102, 'Bags', 2019);

INSERT INTO SONG (SONG_ID, TITLE, RELEASE_YEAR) 
VALUES (103, 'A Pearl', 2018);

INSERT INTO SONG (SONG_ID, TITLE, RELEASE_YEAR) 
VALUES (104, 'Dancing with myself', 1981);

INSERT INTO SONG (SONG_ID, TITLE, RELEASE_YEAR) 
VALUES (105, 'NOKIA', 2025);

/* ---------- SONG-ARTIST LINKS (many-to-many) ---------- */
INSERT INTO song_artist VALUES (101,1);      
INSERT INTO song_artist VALUES (102,2);     
INSERT INTO song_artist VALUES (103,3);      
INSERT INTO song_artist VALUES (104,4);     
INSERT INTO song_artist VALUES (105,5);     



-- RATINGS
INSERT INTO RATING (USER_ID, SONG_ID, RATING, REVIEW, CREATED_AT) 
VALUES (1, 101, 5, 'blahhhhh', CURRENT_TIMESTAMP);

INSERT INTO RATING (USER_ID, SONG_ID, RATING, REVIEW, CREATED_AT) 
VALUES (2, 102, 4, 'blahhhh', CURRENT_TIMESTAMP);

INSERT INTO RATING (USER_ID, SONG_ID, RATING, REVIEW, CREATED_AT) 
VALUES (3, 103, 5, 'blahhhh', CURRENT_TIMESTAMP);

INSERT INTO RATING (USER_ID, SONG_ID, RATING, REVIEW, CREATED_AT) 
VALUES (4, 104, 4, 'blahhhh', CURRENT_TIMESTAMP);

INSERT INTO RATING (USER_ID, SONG_ID, RATING, REVIEW, CREATED_AT) 
VALUES (5, 105, 4, 'blahhhh', CURRENT_TIMESTAMP);